# Generated by Django 3.2.9 on 2022-01-16 05:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('visitorCount', models.IntegerField(blank=True, default=0, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('stars', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user_hotel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels')),
                ('hotel_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='BookingModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('BOOKED', 'забронирован')], default='забронирован', max_length=20)),
                ('checkInDate', models.DateField(auto_now_add=True, null=True)),
                ('checkOutDate', models.DateField(auto_now_add=True, null=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Booking',
            },
        ),
    ]
