# Generated by Django 3.2.9 on 2022-01-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodels',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыт'), ('BOOKED', 'забронирован')], default='забронирован', max_length=20),
        ),
    ]
