# Generated by Django 3.2.9 on 2022-01-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20220111_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
