# Generated by Django 3.2.9 on 2022-01-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodels',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыт'), ('BOOKED', 'забронирован')], default='Открыт', max_length=20),
        ),
    ]
